name: test

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        workspace: ["tsconfig", "denojsonconfig"]
        package: ["tsconfig", "denojsonconfig"]
    continue-on-error: true
    steps:
      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.9.4
      - working-directory: ${{ matrix.workspace }}/packages/${{ matrix.package }}
        run: deno check