name: test

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        workspace: ["tsconfig.json", "deno.json"]
        package: ["tsconfig.json", "deno.json"]
    continue-on-error: true
    name: ${{ matrix.workspace }} + ${{ matrix.package }}
    steps:
      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.*
      - run: deno -v
      - working-directory: ${{ matrix.workspace }}/packages/${{ matrix.package }}
        run: deno check